version: '3.3'
services:
  chat_mysql_service:
    container_name: chat_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'chat_app_db'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: 'ChatPsswd123'
      MYSQL_ROOT_PASSWORD: 'ChatPsswd123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      
  chat_server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - '3000'
    container_name: chat_server
    environment:
      DB_TYPE: 'mysql'
      DATABASE_HOST: chat_mysql_service
      MYSQL_DATABASE: 'chat_app_db'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: 'ChatPsswd123'
      NODE_ENV: 'development'
      MYSQL_PORT: '3306'
    links:
      - chat_mysql_service
    depends_on:
      - chat_mysql_service

volumes:
  my-db:
