version: '3.3'
services:
  db:
    container_name: chat_mysql
    image: mysql:5.7
    restart: always
    hostname: chat_mysql
    environment:
      MYSQL_DATABASE: 'chat_server'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: 'ChatPsswd123'
      MYSQL_ROOT_PASSWORD: 'ChatPsswd123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      
  chat_server:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: chat_server
    ports:
      - 3000:3000
    container_name: chat_server

volumes:
  my-db:
